{% set name = "ansys-rocky-core" %}
{% set version = "0.3.3" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ansys_rocky_core-{{ version }}.tar.gz
  sha256: 4505960f8904d43b9039aefb5652056634fddabb6d9fae3fb12e854eeb98ce3a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.2,<4
    - pip
  run:
    - python >={{ python_min }}
    - importlib-metadata >=4.0
    - pyro5 >=5.13
    - numpy >=1.19,<3.0
    - ansys-tools-path

test:
  imports:
    - ansys.rocky.core
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://rocky.docs.pyansys.com/
  summary: Python client library for Ansys Rocky
  dev_url: https://github.com/ansys/pyrocky
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Adrian-B-Moreira
    - fingeraugusto
    - igortg
